apiVersion: v2
name: tech-challenge-lanchonete-microservice-chart
description: A chart for microservices of Tech Challenge Lanchonete, allowing the creation of an application tied with a database
type: application
version: 0.1.0
appVersion: "1.16.0"
